HW 01 Shell student 28
OSLL/csc-os-fall-2016 pull request #17
Opened 2016-09-25 17:49 UTC by acanna

2016-09-27 10:16 UTC, acanna commented
HW 1 Student 28

2016-09-27 14:03 UTC, krinkin requested changes
требуются доработки

2016-09-27 14:03 UTC, krinkin commented on 28/01/Makefile
> +		find ! -name sh.c ! -name Makeile -delete
make clean deletes makefile (: do you know why?

2016-09-27 14:03 UTC, krinkin commented on 28/01/Makefile
> +		gcc -c sh.c -o sh
are you sure that sh will be executable?

2016-10-04 14:39 UTC, acanna commented
Fixed

2016-10-06 08:01 UTC, merged