homework - 01, student's serial number - 10
OSLL/csc-os-fall-2016 pull request #8
Opened 2016-09-24 19:52 UTC by PaGul

2016-09-27 14:26 UTC, krinkin requested changes
make doesn't work
do you know why?

2016-09-27 15:20 UTC, PaGul commented
@krinkin I use:
make -f Makefile.mk

2016-10-11 05:31 UTC, krinkin commented
Please split pull request by lab. One lab = one pull request

2016-10-24 12:13 UTC, krinkin approved these changes

2016-10-24 12:13 UTC, merged